document.addEventListener("DOMContentLoaded",function(){let e=document.getElementById("gangList"),t=document.getElementById("userList");document.getElementById("backgroundAudio");let a=document.getElementById("clock"),n=document.getElementById("timeCheckPopup"),l=document.getElementById("overlay"),s=document.querySelector(".content"),o=document.getElementById("backgroundAudio"),r=document.getElementById("bgVideo");function d(){l.classList.add("hidden"),document.body.classList.remove("no-scroll"),setTimeout(()=>{l.style.display="none",s&&(s.style.display="block")},500)}function i(){let e=new Date,t=e.getHours(),l=e.getMinutes(),s=`${t}:${l<10?"0":""}${l}`;a.textContent=s,1===t||2===t?n.style.display="block":n.style.display="none"}function c(){fetch("Users.wtf").then(e=>e.text()).then(e=>{let a=e.split("\n").map(e=>e.trim()).filter(Boolean);t.innerHTML="",t.classList.add("card-container"),a.forEach((e,a)=>{let n=document.createElement("div");if(n.classList.add("kcard"),n.style.animationDelay=`${.01*a}s`,e.toLowerCase().includes("(rainbow)")){let l=e.replace("(Rainbow)","").trim();n.innerHTML=`<div class="kcard-body"><p class="rgb-effect">${l}</p></div>`}else n.innerHTML=`<div class="kcard-body"><p>${e}</p></div>`;t.appendChild(n)}),t.scrollTop=0}).catch(e=>console.error("Error loading Users.wtf:",e))}function u(){fetch("Gangs.wtf").then(e=>e.text()).then(t=>{let a=t.split("\n").map(e=>e.trim()).filter(Boolean);e.innerHTML="",e.classList.add("card-container"),a.forEach((t,a)=>{let n=document.createElement("div");if(n.classList.add("kcard"),n.style.animationDelay=`${.01*a}s`,t.toLowerCase().includes("(rainbow)")){let l=t.replace("(Rainbow)","").trim();n.innerHTML=`<div class="kcard-body"><p class="rgb-effect">${l}</p></div>`}else n.innerHTML=`<div class="kcard-body"><p>${t}</p></div>`;e.appendChild(n)}),e.scrollTop=0}).catch(e=>console.error("Error loading Gangs.wtf:",e))}function p(e){return e.replace(/\(Rainbow\)|\(Border\)/gi,"").trim()}o.volume=.3,window.addEventListener("DOMContentLoaded",()=>{document.body.classList.add("no-scroll"),l.style.display="flex",l.style.position="fixed"}),l.addEventListener("click",function e(){try{let t=o.play(),a=r.play();Promise.allSettled([t,a]).then(e=>{let t=e[0],a=e[1];"rejected"===t.status&&console.warn("Audio failed to play:",t.reason),"rejected"===a.status&&console.warn("Video failed to play:",a.reason),d()})}catch(n){console.error("Error during playback:",n),d()}}),c(),u(),setInterval(i,1e3),i(),searchInput.addEventListener("input",function a(){var n,l;let s=searchInput.value.toLowerCase(),o=allUsers.filter(e=>e.toLowerCase().includes(s)),r=allGangs.filter(e=>e.toLowerCase().includes(s));n=o,t.innerHTML="",t.classList.add("card-container"),n.forEach((e,a)=>{let n=document.createElement("div");n.classList.add("kcard"),n.style.animationDelay=`${.01*a}s`,p(e);let l=e.toLowerCase().includes("(rainbow)"),s=e.toLowerCase().includes("(border)"),o=e.replace(/\(Rainbow\)|\(Border\)/gi,"").trim(),r=`
        ${l?'<span class="rgb-effect">':""}
        ${o}
        ${l?"</span>":""}
    `;n.innerHTML=`<div class="kcard-body"><p>${r}</p></div>`,s&&n.classList.add("block"),t.appendChild(n)}),t.scrollTop=0,l=r,e.innerHTML="",e.classList.add("card-container"),l.forEach((t,a)=>{let n=document.createElement("div");n.classList.add("kcard"),n.style.animationDelay=`${.01*a}s`;let l=p(t),s=t.toLowerCase().includes("(rainbow)"),o=`
        ${s?'<span class="rgb-effect">':""}
        ${l}
        ${s?"</span>":""}
    `;n.innerHTML=`<div class="kcard-body"><p>${o}</p></div>`,e.appendChild(n)}),e.scrollTop=0}),c(),u()}),document.addEventListener("DOMContentLoaded",function(){let e=document.getElementById("gangList"),t=document.getElementById("userList"),a=document.getElementById("search-input"),n=document.getElementById("volume-slider"),l=document.getElementById("bgVideo"),s=document.querySelectorAll("audio"),o=[],r=[];function d(e){return e.replace(/\(Border\)|\(Rainbow\)|\(Glow\)/gi,"").trim()}function i(e){t.innerHTML="",t.classList.add("card-container"),e.forEach((e,a)=>{let n=document.createElement("div");n.classList.add("kcard"),n.style.animationDelay=`${.01*a}s`,d(e);let l=e.toLowerCase().includes("(rainbow)"),s=e.toLowerCase().includes("(border)"),o=e.toLowerCase().includes("(glow)"),r=e.replace(/\(Rainbow\)|\(Border\)|\(Glow\)/gi,"").trim(),i=`
            ${l?'<span class="rgb-effect">':""}
            ${o?'<span class="gold-effect">':""}
            ${r}
            ${o?"</span>":""}
            ${l?"</span>":""}
        `;n.innerHTML=`<div class="kcard-body"><p>${i}</p></div>`,o&&n.classList.add("glow"),s&&n.classList.add("block"),t.appendChild(n)}),t.scrollTop=0}function c(t){e.innerHTML="",e.classList.add("card-container"),t.forEach((t,a)=>{let n=document.createElement("div");n.classList.add("kcard"),n.style.animationDelay=`${.01*a}s`;let l=d(t),s=t.toLowerCase().includes("(rainbow)"),o=t.toLowerCase().includes("(glow)"),r=t.toLowerCase().includes("(border)"),i=`
            ${s?'<span class="rgb-effect">':""}
            ${o?'<span class="glow-effect">':""}
            ${l}
            ${o?"</span>":""}
            ${s?"</span>":""}
            `;n.innerHTML=`<div class="kcard-body"><p>${i}</p></div>`,o&&n.classList.add("glow"),r&&n.classList.add("block"),e.appendChild(n)}),e.scrollTop=0}function u(e){s.forEach(t=>{t.volume=e})}document.addEventListener("contextmenu",e=>{e.preventDefault()}),l.addEventListener("contextmenu",e=>{e.preventDefault()}),a.addEventListener("input",function e(){let t=a.value.toLowerCase(),n=o.filter(e=>e.toLowerCase().includes(t)),l=r.filter(e=>e.toLowerCase().includes(t));i(n),c(l)});let p=parseFloat(localStorage.getItem("audioVolume")||.5);n.value=p,u(p),n.addEventListener("input",()=>{var e;let t=parseFloat(n.value);u(t),e=t,localStorage.setItem("audioVolume",e)}),fetch("Users.wtf").then(e=>e.text()).then(e=>{i(o=e.split("\n").map(e=>e.trim()).filter(Boolean))}).catch(e=>console.error("Error loading Users.wtf:",e)),fetch("Gangs.wtf").then(e=>e.text()).then(e=>{c(r=e.split("\n").map(e=>e.trim()).filter(Boolean))}).catch(e=>console.error("Error loading Gangs.wtf:",e))}),document.addEventListener("DOMContentLoaded",function(){let e=document.getElementById("bgVideo");e.addEventListener("fullscreenchange",e=>{document.fullscreenElement&&document.exitFullscreen()}),e.addEventListener("contextmenu",e=>{e.preventDefault()})});const audioElements=document.querySelectorAll("audio"),volumeSlider=document.getElementById("volume-slider");function saveVolumeToLocalStorage(e){localStorage.setItem("audioVolume",e)}function getVolumeFromLocalStorage(){return localStorage.getItem("audioVolume")||.5}function setVolumeForAllAudio(e){audioElements.forEach(t=>{t.volume=e})}document.addEventListener("DOMContentLoaded",()=>{let e=parseFloat(getVolumeFromLocalStorage());volumeSlider.value=e,setVolumeForAllAudio(e),console.log(`Loaded saved volume: ${e}`)}),volumeSlider.addEventListener("input",()=>{let e=parseFloat(volumeSlider.value);setVolumeForAllAudio(e),saveVolumeToLocalStorage(e),console.log(`Volume updated to: ${e}`)}),resetButton.addEventListener("click",async()=>{if(currentUser&&"admin"===currentUser.displayName||"LARP"===currentUser.displayName)try{let e=query(collection(db,"chats")),t=await getDocs(e);t.forEach(async e=>{await deleteDoc(e.ref)}),alert("All messages have been deleted.")}catch(a){errorMsg.textContent="Error resetting messages: "+a.message}});
